name: Automated Tests

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!trunk"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Only docs changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE '^(docs|\.github)'; then
            echo "Only docs changes, exiting"
            exit 0
          fi

      - name: Create scan-processing-d5aa2e71588b.json file
        run: |
          echo '${{ secrets.SERVICE_ACCOUNT_INFO }}' > scan_processing_service/scan-processing-d5aa2e71588b.json
          cat scan_processing_service/scan-processing-d5aa2e71588b.json
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_VALUES }}" > .env
          echo GAC="${{ secrets.GAC }}" >> .env

      - name: Build Docker Compose
        run: docker-compose build

      - name: Run Pytests
        run: docker-compose run --rm scan_processing_service pytest
