name: Automated Tests

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!trunk"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: print git branch -r
        run: git branch -r

      - name: set
        run: git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/trunk

      - name: print git branch -r
        run: git branch -r

      - name: Early exit if only docs changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          if git diff --name-only origin/trunk | grep -vE '^(docs/|README\.md)'; then
            echo "Changes found outside docs or README"
          else
            echo "Only changes in docs or README"
            exit 0
          fi

      - name: Create scan-processing-d5aa2e71588b.json file
        run: |
          echo '${{ secrets.SERVICE_ACCOUNT_INFO }}' > scan_processing_service/scan-processing-d5aa2e71588b.json
          cat scan_processing_service/scan-processing-d5aa2e71588b.json

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_VALUES }}" > .env
          echo GAC="${{ secrets.GAC }}" >> .env

      - name: Build Docker Compose
        run: docker-compose build

      - name: Run Pytests
        run: docker-compose run --rm scan_processing_service pytest
