name: Automated Tests

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create scan-processing-d5aa2e71588b.json file
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_INFO }}" > scan-processing-d5aa2e71588b.json

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_VALUES }}" > .env
          echo GAC="${{ secrets.GAC }}" >> .env

      - name: Build Docker Compose
        run: docker-compose build

      - name: Run Pytests
        run: docker-compose run --rm scan_processing_service pytest
